### ISSUE TITLE
Nodejs client does not work

### ISSUE THREAD

**Issue by KunalSaini** [aspnet/SignalR-samples#49]
I created a basic example based on the sample , however it does not work
```
const signalR = require("@aspnet/signalr");

XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
WebSocket = require("websocket").w3cwebsocket;
 
let connection = new signalR.HubConnectionBuilder()
    .withUrl("http://localhost:61937/signalr/hubs")
    .build();
 
connection.on("send", data => {
    console.log(data);
});
 
connection.start()
    .then(() => connection.invoke("send", "Hello"));
```
error - 
```

module.js:549
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (..../signarlclient/node_modules/@aspnet/signalr/dist/cjs/Errors.js:5:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
node environment 
```
node -v
v10.8.0
npm -v
6.2.0
```

packages installed
```
  "dependencies": {
    "@aspnet/signalr": "^1.0.3",
    "@types/node": "^10.9.4",
    "eventsource": "^1.0.7",
    "websocket": "^1.0.26",
    "xmlhttprequest": "^1.8.0"
  }
```

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/issues/2410

**Comment by KunalSaini** [comment]
Thanks for the workaround mentioned in the link you provided. Closing this issue, however you may want to mention the issue in readme for this (nodejs sample) till its resolved in the npm package.
