### ISSUE TITLE
AndroidJavaClient exception

### ISSUE THREAD

**Issue by pavelveselev** [aspnet/SignalR-samples#86]
I ran AndroidJavaClient sample, and dot an Exception:

2019-04-25 14:01:42.877 15072-15328/com.microsoft.aspnet.signalr.samples.androidjavaclient E/OkHttpWebSocketWrapper: WebSocket closed from an error: Expected HTTP 101 response but was '200 OK'.
2019-04-25 14:01:42.878 15072-15328/com.microsoft.aspnet.signalr.samples.androidjavaclient I/WebSocketTransport: WebSocket connection stopping with code null and reason 'Expected HTTP 101 response but was '200 OK''.
2019-04-25 14:01:42.878 15072-15328/com.microsoft.aspnet.signalr.samples.androidjavaclient E/c*.m*.s*.HubConnection: HubConnection disconnected with an error Expected HTTP 101 response but was '200 OK'.
    
    --------- beginning of crash
2019-04-25 14:01:42.885 15072-15328/com.microsoft.aspnet.signalr.samples.androidjavaclient E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.microsoft.aspnet.signalr.samples.androidjavaclient, PID: 15072
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.signalr.HubConnection$ConnectionState.cancelOutstandingInvocations(java.lang.Exception)' on a null object reference
        at com.microsoft.signalr.HubConnection.stopConnection(HubConnection.java:431)
        at com.microsoft.signalr.HubConnection.lambda$start$6$HubConnection(HubConnection.java:301)
        at com.microsoft.signalr.HubConnection$$Lambda$19.invoke(Unknown Source:2)
        at com.microsoft.signalr.WebSocketTransport.onClose(WebSocketTransport.java:93)
        at com.microsoft.signalr.WebSocketTransport.lambda$start$1$WebSocketTransport(WebSocketTransport.java:56)
        at com.microsoft.signalr.WebSocketTransport$$Lambda$1.invoke(Unknown Source:2)
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:98)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:197)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

I've created simple Xamarin Android project, added this code:

var connection = new HubConnectionBuilder().WithUrl("https://my.site.com").Build();
connection.On<string>("SendInfo", x => Log.Info("SIGNALR", x));
connection.StartAsync();

and everything works fine. How to run AndroidJavaClient correctly?

**Comment by pavelveselev** [comment]
I was using client version 1.0.2 (implementation 'com.microsoft.signalr:signalr:1.0.2'). I've checked out the source and found the line where the error occurs. And it was fixed in commit ff385f71c592ff218956cfa3b1b0a184604b8409. I've found new preview version of SignalR Android Java client: https://search.maven.org/artifact/com.microsoft.signalr/signalr/3.0.0-preview4-19216-03/jar
But, this version also crashes my app with another exception: 
2019-04-29 13:51:00.711 31102-31187/com.microsoft.aspnet.signalr.samples.androidjavaclient E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.microsoft.aspnet.signalr.samples.androidjavaclient, PID: 31102
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: There was an error starting the WebSocket transport.
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.checkStartFailure(OkHttpWebSocketWrapper.java:106)
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:99)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:197)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by BrennanConroy** [comment]
@mikaelm12

**Comment by mikaelm12** [comment]
@pavelveselev First question here is are you sure you have Websockets enabled on your site? By default the SignalR Java client only supports websockets so this is an issue people can run into.

**Comment by pavelveselev** [comment]
@mikaelm12 You're right, Xamarin version was working through LongPolling, and problem was in reverse proxy. I fixed it, and now I have another exception:

    --------- beginning of crash
2019-04-30 13:03:47.207 1553-1553/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 1553
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.microsoft.signalr.HubConnection.<init>(HubConnection.java:156)
        at com.microsoft.signalr.HttpHubConnectionBuilder.build(HttpHubConnectionBuilder.java:122)
        at com.myapp.presentation.MyFragment.onCreate(MyFragment.kt:38)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2528)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:843)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1135)
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1391)
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3123)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:360)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:339)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:819)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:537)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.myapp.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7058)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.microsoft.signalr.HubConnection.<init>(HubConnection.java:156) 
        at com.microsoft.signalr.HttpHubConnectionBuilder.build(HttpHubConnectionBuilder.java:122) 
        at com.myapp.MyFragment.onCreate(MyFragment.kt:38) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2528) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:843) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1135) 
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1391) 
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3123) 
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134) 
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:360) 
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:339) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:819) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:902) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:905) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:554) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:461) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:383) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:537) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at com.myapp.MainActivity.onCreate(MainActivity.kt:16) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7058) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 

I get this exception in every client version I've tried: 1.0.0, 1.0.2, 3.0.0-preview4-19216-03
My code in fragment is this:
override fun onCeate(savedInstanceState: Bundle?) {
...
            hubConnection = HubConnectionBuilder.create("https://mysite.com").build()
            hubConnection?.on("SendTest", { message ->
                Log.i("SIGNALR!", message)
            }, String::class.java)
            HubConnectionTask().execute(hubConnection)
}

internal class HubConnectionTask : AsyncTask<HubConnection, Void, Void>() {
    override fun onPreExecute() {
        super.onPreExecute()
    }
    override fun doInBackground(vararg hubConnections: HubConnection): Void? {
        val hubConnection = hubConnections[0]
        hubConnection.start().blockingAwait()
        return null
    }
}

Transport WebSockets for sure

**Comment by mikaelm12** [comment]
cc @anurse Can you transfer this issue to the main repo
